### PR TITLE
Feature/sushi bsc

### PR DESCRIPTION
**Pull request by nguyenhuudungz**

### CODE REVIEW

**Comment by viet-nv** [comment]
@nguyenhuudungz for the future PRs, Please make it as draft for testing purpose

**Comment by nguyenhuudungz** [comment]
> @nguyenhuudungz for the future PRs, Please make it as draft for testing purpose

does it create a adpr for me with draft pr?

**Comment by viet-nv** [comment]
> es it create a adpr for me with draft pr?

yes. except conflict PRs, the others will have an temporary domain

**Comment by viet-nv** [comment]
Btw, I hear Tu said sushi was released to prod. so when this is done, please close it

**Pull request closed without merging**
