### PR TITLE
Highlight buttons when redirecting from About page

### PR DESCRIPTION
**Pull request by hungdoansy**
# Description
We need to highlight the Add Liquidity button when users click Start Eearning buttons in About page. Also, Kami requested to update the text color of the View Farms button so that the icon and the text share the same color

### CODE REVIEW

**Review by nguyenhoaidanh — APPROVED** [review]
No problem, but params so long 🤧

**Review by namgold — APPROVED** [review]
Lgtm

**Comment by namgold** [comment]
> No problem, but params so long 🤧

shorten them as `hCB` and `hALB` for `highlightCreateButton` and `highlightAddLiquidityButton`?

**Comment by hungdoansy** [comment]
> > No problem, but params so long 🤧
> 
> shorten them as `hCB` and `hALB` for `highlightCreateButton` and `highlightAddLiquidityButton`?

@nguyenhoaidanh @namgold We may not need to care for the length because users won't type it. If we shorten to `hCB` or `hALB`, it's quite hard to immediately infer the meaning of the params

**Comment by namgold** [comment]
Actually we can infer it by assign a const. `const highlightAddLiquidityButton = 'halb'`

This help link shorter, imo this is better

**Comment by namgold** [comment]
User dont type it but they share it @hungdoansy

**Pull request merged**
